# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc
import warnings

from engine.pb import inference_pb2 as inference__pb2

GRPC_GENERATED_VERSION = '1.83.1'
GRPC_VERSION = grpc.__version__
_version_not_supported = False

try:
    from grpc._utilities import first_version_is_lower
    _version_not_supported = first_version_is_lower(GRPC_VERSION, GRPC_GENERATED_VERSION)
except ImportError:
    _version_not_supported = True

if _version_not_supported:
    raise RuntimeError(
        f'The grpc package installed is at version {GRPC_VERSION},'
        + ' but the generated code in inference_pb2_grpc.py depends on'
        + f' grpcio>={GRPC_GENERATED_VERSION}.'
        + f' Please upgrade your grpc module to grpcio>={GRPC_GENERATED_VERSION}'
        + f' or downgrade your generated code using grpcio-tools<={GRPC_VERSION}.'
    )


class InferenceStub:
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.Generate = channel.unary_stream(
                '/nanoserve.v1.Inference/Generate',
                request_serializer=inference__pb2.GenerateRequest.SerializeToString,
                response_deserializer=inference__pb2.GenerateChunk.FromString,
                _registered_method=True)
        self.Health = channel.unary_unary(
                '/nanoserve.v1.Inference/Health',
                request_serializer=inference__pb2.HealthRequest.SerializeToString,
                response_deserializer=inference__pb2.HealthResponse.FromString,
                _registered_method=True)
        self.Drain = channel.unary_unary(
                '/nanoserve.v1.Inference/Drain',
                request_serializer=inference__pb2.DrainRequest.SerializeToString,
                response_deserializer=inference__pb2.DrainResponse.FromString,
                _registered_method=True)


class InferenceServicer:
    """Missing associated documentation comment in .proto file."""

    def Generate(self, request, context):
        """One request, a stream of tokens.
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def Health(self, request, context):
        """Liveness plus the load signal the router routes on. Deliberately cheap:
        the router polls this often, and a health check that takes a lock or
        touches the GPU becomes the thing that makes a replica look unhealthy.
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def Drain(self, request, context):
        """Ask a replica to stop accepting work and finish what it has. Used by the
        graceful-drain path so a deploy does not kill in-flight generations.
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_InferenceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'Generate': grpc.unary_stream_rpc_method_handler(
                    servicer.Generate,
                    request_deserializer=inference__pb2.GenerateRequest.FromString,
                    response_serializer=inference__pb2.GenerateChunk.SerializeToString,
            ),
            'Health': grpc.unary_unary_rpc_method_handler(
                    servicer.Health,
                    request_deserializer=inference__pb2.HealthRequest.FromString,
                    response_serializer=inference__pb2.HealthResponse.SerializeToString,
            ),
            'Drain': grpc.unary_unary_rpc_method_handler(
                    servicer.Drain,
                    request_deserializer=inference__pb2.DrainRequest.FromString,
                    response_serializer=inference__pb2.DrainResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'nanoserve.v1.Inference', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('nanoserve.v1.Inference', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class Inference:
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def Generate(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_stream(
            request,
            target,
            '/nanoserve.v1.Inference/Generate',
            inference__pb2.GenerateRequest.SerializeToString,
            inference__pb2.GenerateChunk.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def Health(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/nanoserve.v1.Inference/Health',
            inference__pb2.HealthRequest.SerializeToString,
            inference__pb2.HealthResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def Drain(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/nanoserve.v1.Inference/Drain',
            inference__pb2.DrainRequest.SerializeToString,
            inference__pb2.DrainResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
