// The router <-> replica contract.
//
// Server-streaming, not unary. A unary RPC would hold the whole generation
// before returning anything, which throws away the one latency number users
// actually feel: time to first token. Streaming also lets the router notice a
// dead replica mid-generation rather than at a timeout.
//
// gRPC rather than HTTP chunking because the router holds thousands of
// concurrent streams: HTTP/2 multiplexes them over one connection per replica
// instead of one socket each, and protobuf framing removes the need to parse
// SSE text on a hot path.

// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.12
// 	protoc        v7.35.1
// source: inference.proto

package router

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type Finish_Reason int32

const (
	Finish_REASON_UNSPECIFIED Finish_Reason = 0
	Finish_EOS                Finish_Reason = 1
	Finish_LENGTH             Finish_Reason = 2
	Finish_CANCELLED          Finish_Reason = 3
	Finish_REJECTED           Finish_Reason = 4
	Finish_PREEMPTED          Finish_Reason = 5
	Finish_ERROR              Finish_Reason = 6
)

// Enum value maps for Finish_Reason.
var (
	Finish_Reason_name = map[int32]string{
		0: "REASON_UNSPECIFIED",
		1: "EOS",
		2: "LENGTH",
		3: "CANCELLED",
		4: "REJECTED",
		5: "PREEMPTED",
		6: "ERROR",
	}
	Finish_Reason_value = map[string]int32{
		"REASON_UNSPECIFIED": 0,
		"EOS":                1,
		"LENGTH":             2,
		"CANCELLED":          3,
		"REJECTED":           4,
		"PREEMPTED":          5,
		"ERROR":              6,
	}
)

func (x Finish_Reason) Enum() *Finish_Reason {
	p := new(Finish_Reason)
	*p = x
	return p
}

func (x Finish_Reason) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (Finish_Reason) Descriptor() protoreflect.EnumDescriptor {
	return file_inference_proto_enumTypes[0].Descriptor()
}

func (Finish_Reason) Type() protoreflect.EnumType {
	return &file_inference_proto_enumTypes[0]
}

func (x Finish_Reason) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use Finish_Reason.Descriptor instead.
func (Finish_Reason) EnumDescriptor() ([]byte, []int) {
	return file_inference_proto_rawDescGZIP(), []int{4, 0}
}

type SamplingParams struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	MaxTokens     uint32                 `protobuf:"varint,1,opt,name=max_tokens,json=maxTokens,proto3" json:"max_tokens,omitempty"`
	Temperature   float32                `protobuf:"fixed32,2,opt,name=temperature,proto3" json:"temperature,omitempty"`
	TopK          uint32                 `protobuf:"varint,3,opt,name=top_k,json=topK,proto3" json:"top_k,omitempty"`  // 0 means unset
	TopP          float32                `protobuf:"fixed32,4,opt,name=top_p,json=topP,proto3" json:"top_p,omitempty"` // 0 means unset
	IgnoreEos     bool                   `protobuf:"varint,5,opt,name=ignore_eos,json=ignoreEos,proto3" json:"ignore_eos,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SamplingParams) Reset() {
	*x = SamplingParams{}
	mi := &file_inference_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SamplingParams) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SamplingParams) ProtoMessage() {}

func (x *SamplingParams) ProtoReflect() protoreflect.Message {
	mi := &file_inference_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SamplingParams.ProtoReflect.Descriptor instead.
func (*SamplingParams) Descriptor() ([]byte, []int) {
	return file_inference_proto_rawDescGZIP(), []int{0}
}

func (x *SamplingParams) GetMaxTokens() uint32 {
	if x != nil {
		return x.MaxTokens
	}
	return 0
}

func (x *SamplingParams) GetTemperature() float32 {
	if x != nil {
		return x.Temperature
	}
	return 0
}

func (x *SamplingParams) GetTopK() uint32 {
	if x != nil {
		return x.TopK
	}
	return 0
}

func (x *SamplingParams) GetTopP() float32 {
	if x != nil {
		return x.TopP
	}
	return 0
}

func (x *SamplingParams) GetIgnoreEos() bool {
	if x != nil {
		return x.IgnoreEos
	}
	return false
}

type GenerateRequest struct {
	state  protoimpl.MessageState `protogen:"open.v1"`
	Prompt string                 `protobuf:"bytes,1,opt,name=prompt,proto3" json:"prompt,omitempty"`
	Params *SamplingParams        `protobuf:"bytes,2,opt,name=params,proto3" json:"params,omitempty"`
	// Idempotency key. A retry after a replica dies carries the SAME id, so a
	// replica that already has it returns the existing stream rather than
	// starting a second generation. Without this, every retry doubles the work
	// the cluster does at exactly the moment it is least able to afford it.
	RequestId string `protobuf:"bytes,3,opt,name=request_id,json=requestId,proto3" json:"request_id,omitempty"`
	// Absolute deadline, Unix epoch seconds. Absolute rather than a duration so
	// it survives queueing at the router: a "5 second" budget restarted at each
	// hop is not a budget.
	DeadlineUnix float64 `protobuf:"fixed64,4,opt,name=deadline_unix,json=deadlineUnix,proto3" json:"deadline_unix,omitempty"`
	// Tokens the client has already received from a previous, failed attempt.
	// On migration the router replays prompt + these, so the new replica
	// continues rather than restarting, and the client never sees a token twice.
	ResumeTokens  []uint32 `protobuf:"varint,5,rep,packed,name=resume_tokens,json=resumeTokens,proto3" json:"resume_tokens,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GenerateRequest) Reset() {
	*x = GenerateRequest{}
	mi := &file_inference_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GenerateRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GenerateRequest) ProtoMessage() {}

func (x *GenerateRequest) ProtoReflect() protoreflect.Message {
	mi := &file_inference_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GenerateRequest.ProtoReflect.Descriptor instead.
func (*GenerateRequest) Descriptor() ([]byte, []int) {
	return file_inference_proto_rawDescGZIP(), []int{1}
}

func (x *GenerateRequest) GetPrompt() string {
	if x != nil {
		return x.Prompt
	}
	return ""
}

func (x *GenerateRequest) GetParams() *SamplingParams {
	if x != nil {
		return x.Params
	}
	return nil
}

func (x *GenerateRequest) GetRequestId() string {
	if x != nil {
		return x.RequestId
	}
	return ""
}

func (x *GenerateRequest) GetDeadlineUnix() float64 {
	if x != nil {
		return x.DeadlineUnix
	}
	return 0
}

func (x *GenerateRequest) GetResumeTokens() []uint32 {
	if x != nil {
		return x.ResumeTokens
	}
	return nil
}

type GenerateChunk struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Types that are valid to be assigned to Payload:
	//
	//	*GenerateChunk_Token
	//	*GenerateChunk_Finish
	Payload       isGenerateChunk_Payload `protobuf_oneof:"payload"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GenerateChunk) Reset() {
	*x = GenerateChunk{}
	mi := &file_inference_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GenerateChunk) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GenerateChunk) ProtoMessage() {}

func (x *GenerateChunk) ProtoReflect() protoreflect.Message {
	mi := &file_inference_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GenerateChunk.ProtoReflect.Descriptor instead.
func (*GenerateChunk) Descriptor() ([]byte, []int) {
	return file_inference_proto_rawDescGZIP(), []int{2}
}

func (x *GenerateChunk) GetPayload() isGenerateChunk_Payload {
	if x != nil {
		return x.Payload
	}
	return nil
}

func (x *GenerateChunk) GetToken() *Token {
	if x != nil {
		if x, ok := x.Payload.(*GenerateChunk_Token); ok {
			return x.Token
		}
	}
	return nil
}

func (x *GenerateChunk) GetFinish() *Finish {
	if x != nil {
		if x, ok := x.Payload.(*GenerateChunk_Finish); ok {
			return x.Finish
		}
	}
	return nil
}

type isGenerateChunk_Payload interface {
	isGenerateChunk_Payload()
}

type GenerateChunk_Token struct {
	Token *Token `protobuf:"bytes,1,opt,name=token,proto3,oneof"`
}

type GenerateChunk_Finish struct {
	Finish *Finish `protobuf:"bytes,2,opt,name=finish,proto3,oneof"`
}

func (*GenerateChunk_Token) isGenerateChunk_Payload() {}

func (*GenerateChunk_Finish) isGenerateChunk_Payload() {}

type Token struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Decoded text for this step. May be empty when a token completes only part
	// of a multi-byte character -- the replica holds those back rather than
	// emitting a replacement character mid-word.
	Text    string `protobuf:"bytes,1,opt,name=text,proto3" json:"text,omitempty"`
	TokenId uint32 `protobuf:"varint,2,opt,name=token_id,json=tokenId,proto3" json:"token_id,omitempty"`
	// Position in the output, so a migrating router knows what it already has.
	Index         uint32 `protobuf:"varint,3,opt,name=index,proto3" json:"index,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Token) Reset() {
	*x = Token{}
	mi := &file_inference_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Token) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Token) ProtoMessage() {}

func (x *Token) ProtoReflect() protoreflect.Message {
	mi := &file_inference_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Token.ProtoReflect.Descriptor instead.
func (*Token) Descriptor() ([]byte, []int) {
	return file_inference_proto_rawDescGZIP(), []int{3}
}

func (x *Token) GetText() string {
	if x != nil {
		return x.Text
	}
	return ""
}

func (x *Token) GetTokenId() uint32 {
	if x != nil {
		return x.TokenId
	}
	return 0
}

func (x *Token) GetIndex() uint32 {
	if x != nil {
		return x.Index
	}
	return 0
}

type Finish struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Reason        Finish_Reason          `protobuf:"varint,1,opt,name=reason,proto3,enum=nanoserve.v1.Finish_Reason" json:"reason,omitempty"`
	OutputTokens  uint32                 `protobuf:"varint,2,opt,name=output_tokens,json=outputTokens,proto3" json:"output_tokens,omitempty"`
	Message       string                 `protobuf:"bytes,3,opt,name=message,proto3" json:"message,omitempty"` // set when reason is REJECTED or ERROR
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Finish) Reset() {
	*x = Finish{}
	mi := &file_inference_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Finish) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Finish) ProtoMessage() {}

func (x *Finish) ProtoReflect() protoreflect.Message {
	mi := &file_inference_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Finish.ProtoReflect.Descriptor instead.
func (*Finish) Descriptor() ([]byte, []int) {
	return file_inference_proto_rawDescGZIP(), []int{4}
}

func (x *Finish) GetReason() Finish_Reason {
	if x != nil {
		return x.Reason
	}
	return Finish_REASON_UNSPECIFIED
}

func (x *Finish) GetOutputTokens() uint32 {
	if x != nil {
		return x.OutputTokens
	}
	return 0
}

func (x *Finish) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

type HealthRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *HealthRequest) Reset() {
	*x = HealthRequest{}
	mi := &file_inference_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *HealthRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*HealthRequest) ProtoMessage() {}

func (x *HealthRequest) ProtoReflect() protoreflect.Message {
	mi := &file_inference_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use HealthRequest.ProtoReflect.Descriptor instead.
func (*HealthRequest) Descriptor() ([]byte, []int) {
	return file_inference_proto_rawDescGZIP(), []int{5}
}

type HealthResponse struct {
	state    protoimpl.MessageState `protogen:"open.v1"`
	Ready    bool                   `protobuf:"varint,1,opt,name=ready,proto3" json:"ready,omitempty"` // false while loading, or draining
	Draining bool                   `protobuf:"varint,2,opt,name=draining,proto3" json:"draining,omitempty"`
	// The load signal. Bounded-load routing compares in-flight work against the
	// cluster mean, so the router needs a number that means the same thing on
	// every replica -- sequences currently generating.
	NumRunning uint32 `protobuf:"varint,3,opt,name=num_running,json=numRunning,proto3" json:"num_running,omitempty"`
	NumWaiting uint32 `protobuf:"varint,4,opt,name=num_waiting,json=numWaiting,proto3" json:"num_waiting,omitempty"`
	// 0-1. KV pressure is the real capacity limit for a serving replica, and it
	// is not visible in CPU or request count.
	KvUtilization float32 `protobuf:"fixed32,5,opt,name=kv_utilization,json=kvUtilization,proto3" json:"kv_utilization,omitempty"`
	// Lets the router prefer a replica that already holds a prefix.
	PrefixHitRate float32 `protobuf:"fixed32,6,opt,name=prefix_hit_rate,json=prefixHitRate,proto3" json:"prefix_hit_rate,omitempty"`
	ReplicaId     string  `protobuf:"bytes,7,opt,name=replica_id,json=replicaId,proto3" json:"replica_id,omitempty"`
	UptimeSeconds uint64  `protobuf:"varint,8,opt,name=uptime_seconds,json=uptimeSeconds,proto3" json:"uptime_seconds,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *HealthResponse) Reset() {
	*x = HealthResponse{}
	mi := &file_inference_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *HealthResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*HealthResponse) ProtoMessage() {}

func (x *HealthResponse) ProtoReflect() protoreflect.Message {
	mi := &file_inference_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use HealthResponse.ProtoReflect.Descriptor instead.
func (*HealthResponse) Descriptor() ([]byte, []int) {
	return file_inference_proto_rawDescGZIP(), []int{6}
}

func (x *HealthResponse) GetReady() bool {
	if x != nil {
		return x.Ready
	}
	return false
}

func (x *HealthResponse) GetDraining() bool {
	if x != nil {
		return x.Draining
	}
	return false
}

func (x *HealthResponse) GetNumRunning() uint32 {
	if x != nil {
		return x.NumRunning
	}
	return 0
}

func (x *HealthResponse) GetNumWaiting() uint32 {
	if x != nil {
		return x.NumWaiting
	}
	return 0
}

func (x *HealthResponse) GetKvUtilization() float32 {
	if x != nil {
		return x.KvUtilization
	}
	return 0
}

func (x *HealthResponse) GetPrefixHitRate() float32 {
	if x != nil {
		return x.PrefixHitRate
	}
	return 0
}

func (x *HealthResponse) GetReplicaId() string {
	if x != nil {
		return x.ReplicaId
	}
	return ""
}

func (x *HealthResponse) GetUptimeSeconds() uint64 {
	if x != nil {
		return x.UptimeSeconds
	}
	return 0
}

type DrainRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Stop accepting, finish in-flight, then exit. The router removes the
	// replica from rotation as soon as draining is reported.
	Graceful      bool `protobuf:"varint,1,opt,name=graceful,proto3" json:"graceful,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DrainRequest) Reset() {
	*x = DrainRequest{}
	mi := &file_inference_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DrainRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DrainRequest) ProtoMessage() {}

func (x *DrainRequest) ProtoReflect() protoreflect.Message {
	mi := &file_inference_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DrainRequest.ProtoReflect.Descriptor instead.
func (*DrainRequest) Descriptor() ([]byte, []int) {
	return file_inference_proto_rawDescGZIP(), []int{7}
}

func (x *DrainRequest) GetGraceful() bool {
	if x != nil {
		return x.Graceful
	}
	return false
}

type DrainResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	InFlight      uint32                 `protobuf:"varint,1,opt,name=in_flight,json=inFlight,proto3" json:"in_flight,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DrainResponse) Reset() {
	*x = DrainResponse{}
	mi := &file_inference_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DrainResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DrainResponse) ProtoMessage() {}

func (x *DrainResponse) ProtoReflect() protoreflect.Message {
	mi := &file_inference_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DrainResponse.ProtoReflect.Descriptor instead.
func (*DrainResponse) Descriptor() ([]byte, []int) {
	return file_inference_proto_rawDescGZIP(), []int{8}
}

func (x *DrainResponse) GetInFlight() uint32 {
	if x != nil {
		return x.InFlight
	}
	return 0
}

var File_inference_proto protoreflect.FileDescriptor

const file_inference_proto_rawDesc = "" +
	"\n" +
	"\x0finference.proto\x12\fnanoserve.v1\"\x9a\x01\n" +
	"\x0eSamplingParams\x12\x1d\n" +
	"\n" +
	"max_tokens\x18\x01 \x01(\rR\tmaxTokens\x12 \n" +
	"\vtemperature\x18\x02 \x01(\x02R\vtemperature\x12\x13\n" +
	"\x05top_k\x18\x03 \x01(\rR\x04topK\x12\x13\n" +
	"\x05top_p\x18\x04 \x01(\x02R\x04topP\x12\x1d\n" +
	"\n" +
	"ignore_eos\x18\x05 \x01(\bR\tignoreEos\"\xc8\x01\n" +
	"\x0fGenerateRequest\x12\x16\n" +
	"\x06prompt\x18\x01 \x01(\tR\x06prompt\x124\n" +
	"\x06params\x18\x02 \x01(\v2\x1c.nanoserve.v1.SamplingParamsR\x06params\x12\x1d\n" +
	"\n" +
	"request_id\x18\x03 \x01(\tR\trequestId\x12#\n" +
	"\rdeadline_unix\x18\x04 \x01(\x01R\fdeadlineUnix\x12#\n" +
	"\rresume_tokens\x18\x05 \x03(\rR\fresumeTokens\"w\n" +
	"\rGenerateChunk\x12+\n" +
	"\x05token\x18\x01 \x01(\v2\x13.nanoserve.v1.TokenH\x00R\x05token\x12.\n" +
	"\x06finish\x18\x02 \x01(\v2\x14.nanoserve.v1.FinishH\x00R\x06finishB\t\n" +
	"\apayload\"L\n" +
	"\x05Token\x12\x12\n" +
	"\x04text\x18\x01 \x01(\tR\x04text\x12\x19\n" +
	"\btoken_id\x18\x02 \x01(\rR\atokenId\x12\x14\n" +
	"\x05index\x18\x03 \x01(\rR\x05index\"\xea\x01\n" +
	"\x06Finish\x123\n" +
	"\x06reason\x18\x01 \x01(\x0e2\x1b.nanoserve.v1.Finish.ReasonR\x06reason\x12#\n" +
	"\routput_tokens\x18\x02 \x01(\rR\foutputTokens\x12\x18\n" +
	"\amessage\x18\x03 \x01(\tR\amessage\"l\n" +
	"\x06Reason\x12\x16\n" +
	"\x12REASON_UNSPECIFIED\x10\x00\x12\a\n" +
	"\x03EOS\x10\x01\x12\n" +
	"\n" +
	"\x06LENGTH\x10\x02\x12\r\n" +
	"\tCANCELLED\x10\x03\x12\f\n" +
	"\bREJECTED\x10\x04\x12\r\n" +
	"\tPREEMPTED\x10\x05\x12\t\n" +
	"\x05ERROR\x10\x06\"\x0f\n" +
	"\rHealthRequest\"\x99\x02\n" +
	"\x0eHealthResponse\x12\x14\n" +
	"\x05ready\x18\x01 \x01(\bR\x05ready\x12\x1a\n" +
	"\bdraining\x18\x02 \x01(\bR\bdraining\x12\x1f\n" +
	"\vnum_running\x18\x03 \x01(\rR\n" +
	"numRunning\x12\x1f\n" +
	"\vnum_waiting\x18\x04 \x01(\rR\n" +
	"numWaiting\x12%\n" +
	"\x0ekv_utilization\x18\x05 \x01(\x02R\rkvUtilization\x12&\n" +
	"\x0fprefix_hit_rate\x18\x06 \x01(\x02R\rprefixHitRate\x12\x1d\n" +
	"\n" +
	"replica_id\x18\a \x01(\tR\treplicaId\x12%\n" +
	"\x0euptime_seconds\x18\b \x01(\x04R\ruptimeSeconds\"*\n" +
	"\fDrainRequest\x12\x1a\n" +
	"\bgraceful\x18\x01 \x01(\bR\bgraceful\",\n" +
	"\rDrainResponse\x12\x1b\n" +
	"\tin_flight\x18\x01 \x01(\rR\binFlight2\xdc\x01\n" +
	"\tInference\x12H\n" +
	"\bGenerate\x12\x1d.nanoserve.v1.GenerateRequest\x1a\x1b.nanoserve.v1.GenerateChunk0\x01\x12C\n" +
	"\x06Health\x12\x1b.nanoserve.v1.HealthRequest\x1a\x1c.nanoserve.v1.HealthResponse\x12@\n" +
	"\x05Drain\x12\x1a.nanoserve.v1.DrainRequest\x1a\x1b.nanoserve.v1.DrainResponseB$Z\"github.com/nanoserve/router;routerb\x06proto3"

var (
	file_inference_proto_rawDescOnce sync.Once
	file_inference_proto_rawDescData []byte
)

func file_inference_proto_rawDescGZIP() []byte {
	file_inference_proto_rawDescOnce.Do(func() {
		file_inference_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_inference_proto_rawDesc), len(file_inference_proto_rawDesc)))
	})
	return file_inference_proto_rawDescData
}

var file_inference_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_inference_proto_msgTypes = make([]protoimpl.MessageInfo, 9)
var file_inference_proto_goTypes = []any{
	(Finish_Reason)(0),      // 0: nanoserve.v1.Finish.Reason
	(*SamplingParams)(nil),  // 1: nanoserve.v1.SamplingParams
	(*GenerateRequest)(nil), // 2: nanoserve.v1.GenerateRequest
	(*GenerateChunk)(nil),   // 3: nanoserve.v1.GenerateChunk
	(*Token)(nil),           // 4: nanoserve.v1.Token
	(*Finish)(nil),          // 5: nanoserve.v1.Finish
	(*HealthRequest)(nil),   // 6: nanoserve.v1.HealthRequest
	(*HealthResponse)(nil),  // 7: nanoserve.v1.HealthResponse
	(*DrainRequest)(nil),    // 8: nanoserve.v1.DrainRequest
	(*DrainResponse)(nil),   // 9: nanoserve.v1.DrainResponse
}
var file_inference_proto_depIdxs = []int32{
	1, // 0: nanoserve.v1.GenerateRequest.params:type_name -> nanoserve.v1.SamplingParams
	4, // 1: nanoserve.v1.GenerateChunk.token:type_name -> nanoserve.v1.Token
	5, // 2: nanoserve.v1.GenerateChunk.finish:type_name -> nanoserve.v1.Finish
	0, // 3: nanoserve.v1.Finish.reason:type_name -> nanoserve.v1.Finish.Reason
	2, // 4: nanoserve.v1.Inference.Generate:input_type -> nanoserve.v1.GenerateRequest
	6, // 5: nanoserve.v1.Inference.Health:input_type -> nanoserve.v1.HealthRequest
	8, // 6: nanoserve.v1.Inference.Drain:input_type -> nanoserve.v1.DrainRequest
	3, // 7: nanoserve.v1.Inference.Generate:output_type -> nanoserve.v1.GenerateChunk
	7, // 8: nanoserve.v1.Inference.Health:output_type -> nanoserve.v1.HealthResponse
	9, // 9: nanoserve.v1.Inference.Drain:output_type -> nanoserve.v1.DrainResponse
	7, // [7:10] is the sub-list for method output_type
	4, // [4:7] is the sub-list for method input_type
	4, // [4:4] is the sub-list for extension type_name
	4, // [4:4] is the sub-list for extension extendee
	0, // [0:4] is the sub-list for field type_name
}

func init() { file_inference_proto_init() }
func file_inference_proto_init() {
	if File_inference_proto != nil {
		return
	}
	file_inference_proto_msgTypes[2].OneofWrappers = []any{
		(*GenerateChunk_Token)(nil),
		(*GenerateChunk_Finish)(nil),
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_inference_proto_rawDesc), len(file_inference_proto_rawDesc)),
			NumEnums:      1,
			NumMessages:   9,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_inference_proto_goTypes,
		DependencyIndexes: file_inference_proto_depIdxs,
		EnumInfos:         file_inference_proto_enumTypes,
		MessageInfos:      file_inference_proto_msgTypes,
	}.Build()
	File_inference_proto = out.File
	file_inference_proto_goTypes = nil
	file_inference_proto_depIdxs = nil
}
