// The router <-> replica contract.
//
// Server-streaming, not unary. A unary RPC would hold the whole generation
// before returning anything, which throws away the one latency number users
// actually feel: time to first token. Streaming also lets the router notice a
// dead replica mid-generation rather than at a timeout.
//
// gRPC rather than HTTP chunking because the router holds thousands of
// concurrent streams: HTTP/2 multiplexes them over one connection per replica
// instead of one socket each, and protobuf framing removes the need to parse
// SSE text on a hot path.

// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.6.2
// - protoc             v7.35.1
// source: inference.proto

package router

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	Inference_Generate_FullMethodName = "/nanoserve.v1.Inference/Generate"
	Inference_Health_FullMethodName   = "/nanoserve.v1.Inference/Health"
	Inference_Drain_FullMethodName    = "/nanoserve.v1.Inference/Drain"
)

// InferenceClient is the client API for Inference service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type InferenceClient interface {
	// One request, a stream of tokens.
	Generate(ctx context.Context, in *GenerateRequest, opts ...grpc.CallOption) (grpc.ServerStreamingClient[GenerateChunk], error)
	// Liveness plus the load signal the router routes on. Deliberately cheap:
	// the router polls this often, and a health check that takes a lock or
	// touches the GPU becomes the thing that makes a replica look unhealthy.
	Health(ctx context.Context, in *HealthRequest, opts ...grpc.CallOption) (*HealthResponse, error)
	// Ask a replica to stop accepting work and finish what it has. Used by the
	// graceful-drain path so a deploy does not kill in-flight generations.
	Drain(ctx context.Context, in *DrainRequest, opts ...grpc.CallOption) (*DrainResponse, error)
}

type inferenceClient struct {
	cc grpc.ClientConnInterface
}

func NewInferenceClient(cc grpc.ClientConnInterface) InferenceClient {
	return &inferenceClient{cc}
}

func (c *inferenceClient) Generate(ctx context.Context, in *GenerateRequest, opts ...grpc.CallOption) (grpc.ServerStreamingClient[GenerateChunk], error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	stream, err := c.cc.NewStream(ctx, &Inference_ServiceDesc.Streams[0], Inference_Generate_FullMethodName, cOpts...)
	if err != nil {
		return nil, err
	}
	x := &grpc.GenericClientStream[GenerateRequest, GenerateChunk]{ClientStream: stream}
	if err := x.ClientStream.SendMsg(in); err != nil {
		return nil, err
	}
	if err := x.ClientStream.CloseSend(); err != nil {
		return nil, err
	}
	return x, nil
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type Inference_GenerateClient = grpc.ServerStreamingClient[GenerateChunk]

func (c *inferenceClient) Health(ctx context.Context, in *HealthRequest, opts ...grpc.CallOption) (*HealthResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(HealthResponse)
	err := c.cc.Invoke(ctx, Inference_Health_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *inferenceClient) Drain(ctx context.Context, in *DrainRequest, opts ...grpc.CallOption) (*DrainResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(DrainResponse)
	err := c.cc.Invoke(ctx, Inference_Drain_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// InferenceServer is the server API for Inference service.
// All implementations must embed UnimplementedInferenceServer
// for forward compatibility.
type InferenceServer interface {
	// One request, a stream of tokens.
	Generate(*GenerateRequest, grpc.ServerStreamingServer[GenerateChunk]) error
	// Liveness plus the load signal the router routes on. Deliberately cheap:
	// the router polls this often, and a health check that takes a lock or
	// touches the GPU becomes the thing that makes a replica look unhealthy.
	Health(context.Context, *HealthRequest) (*HealthResponse, error)
	// Ask a replica to stop accepting work and finish what it has. Used by the
	// graceful-drain path so a deploy does not kill in-flight generations.
	Drain(context.Context, *DrainRequest) (*DrainResponse, error)
	mustEmbedUnimplementedInferenceServer()
}

// UnimplementedInferenceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedInferenceServer struct{}

func (UnimplementedInferenceServer) Generate(*GenerateRequest, grpc.ServerStreamingServer[GenerateChunk]) error {
	return status.Error(codes.Unimplemented, "method Generate not implemented")
}
func (UnimplementedInferenceServer) Health(context.Context, *HealthRequest) (*HealthResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method Health not implemented")
}
func (UnimplementedInferenceServer) Drain(context.Context, *DrainRequest) (*DrainResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method Drain not implemented")
}
func (UnimplementedInferenceServer) mustEmbedUnimplementedInferenceServer() {}
func (UnimplementedInferenceServer) testEmbeddedByValue()                   {}

// UnsafeInferenceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to InferenceServer will
// result in compilation errors.
type UnsafeInferenceServer interface {
	mustEmbedUnimplementedInferenceServer()
}

func RegisterInferenceServer(s grpc.ServiceRegistrar, srv InferenceServer) {
	// If the following call panics, it indicates UnimplementedInferenceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&Inference_ServiceDesc, srv)
}

func _Inference_Generate_Handler(srv interface{}, stream grpc.ServerStream) error {
	m := new(GenerateRequest)
	if err := stream.RecvMsg(m); err != nil {
		return err
	}
	return srv.(InferenceServer).Generate(m, &grpc.GenericServerStream[GenerateRequest, GenerateChunk]{ServerStream: stream})
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type Inference_GenerateServer = grpc.ServerStreamingServer[GenerateChunk]

func _Inference_Health_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(HealthRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(InferenceServer).Health(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Inference_Health_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(InferenceServer).Health(ctx, req.(*HealthRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Inference_Drain_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(DrainRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(InferenceServer).Drain(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Inference_Drain_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(InferenceServer).Drain(ctx, req.(*DrainRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// Inference_ServiceDesc is the grpc.ServiceDesc for Inference service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var Inference_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "nanoserve.v1.Inference",
	HandlerType: (*InferenceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Health",
			Handler:    _Inference_Health_Handler,
		},
		{
			MethodName: "Drain",
			Handler:    _Inference_Drain_Handler,
		},
	},
	Streams: []grpc.StreamDesc{
		{
			StreamName:    "Generate",
			Handler:       _Inference_Generate_Handler,
			ServerStreams: true,
		},
	},
	Metadata: "inference.proto",
}
